module.exports = {
  purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        azure: "#5383e8",
        customGray: "#EAEAEA",
        lankGray: "#e0e3e3",
        lankBorderGray: "#ced3d3",
        lankTextGray: "#657070",
        lankTextYellow: "#eabd56",
        layoutBorderColor: "#c6cbcb",
        soloRatingText: "#879292",
        soloRatingTextBlue: "#1f8ecd",
        soloRatingTextGray: "#555e5e",
        soloRatingBoxBackground: "#f2f2f2",
        soloRatingBoxBorder: "#cdd2d2",
        championInfoBg: "#ededed",
        winGraph: "#3d95e5",
        winGraphBorder: "#3480c6",
        loseGraph: "#ee5a52",
        loseGraphBorder: "#c6443e",
        gameAvgGreen: "#2daf7f",
        gameAvgYellow: "#e19205",
        gameListRedBg: "#e2b6b3",
        gameListRedBorder: "#cea7a7",
        gameListRedMoreBg: "#e89d99",
        gameListRedMoreBorder: "#d67b77",
        gameListBlueBg: "#a3cfec",
        gameListBlueBorder: "#99b9cf",
        gameListBlueMoreBg: "#64b1e4",
        gameListBlueMoreBorder: "#4aa1d2",
        gameTextBlack: "#353a3a",
        gameBadgeBg: "#8c51c5",
        gameBadgeBorder: "#7f3590",
        gameMoreRed: "#C6453F",
        gameMoreBlue: "#07669F",
        kdaBlue: "#1f8ecd",
        kdaGreen: "#2daf7f",
        gameWinBlue: "#1a78ae",
        tooltipColor: "#222727",
        tabDisableColor: "#9c9c9c",
        tabDisableBg: "#e3e3e3",
        tabActiveColor: "#4a4a4a",
        recentSearchColor: "#666",
        championColor: "#999999",
        positionColor: "#333333",
        tabColor: "#555555",
      },
      keyframes: {
        tooltip: {
          "0%": { opacity: 0 },
          "40%": { opacity: 0 },
          "50%": { opacity: 1 },
          "100%": { opacity: 1 },
        },
      },
      animation: {
        tooltip: "tooltip 0.5s ease-in-out",
      },
      height: {
        px8: "8px",
        px16: "16px",
        px32: "32px",
        px40: "40px",
        px48: "48px",
        px97: "97px",
      },
      width: {
        px8: "8px",
        px16: "16px",
        px32: "32px",
        px48: "48px",
        px97: "97px",
        px141: "141px",
        px200: "200px",
        px260: "260px",
        px300: "300px",
        px690: "690px",
        px990: "990px",
      },
      padding: {
        px2: "2px",
        px8: "8px",
        px9: "9px",
        px14: "14px",
        px42: "42px",
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
